package com.unilever.julia.components.enums

enum class ComponentsType {
    JULIA_LOAD,
    CHAT_MESSAGE_INICIO,
    BUTTON,
    CHIT_CHAT,
    INNOVATION_CARD_VERTICAL,
    INNOVATION_CARD_HORIZONTAL,
    STATUS_PEDIDO,
    AGENDA,
    ADICIONAR_AGENDA,
    JULIA_ANSWER,
    USER_CHAT,
    PEDIDO_CLIENTE_MESSAGE,
    REUNIAO_OUTLOOK,
    CARD_AGENDA_EDICAO,
    FEEDBACK_OPTIONS,
    BUTTON_HORIZONTAL,
    BUTTON_DISAMBIGUATION,
    STATUS_PEDIDO_CARTEIRA,
    IPV,
    AUTO_COMPLETE_CUSTOMERS,
    AUTO_COMPLETE_TERRITORIES,
    DISAMBIGUATION_COD_PEDIDO,
    BOLETIM_CARD_CHAT
}